version: '3.7'

networks:
  directus:
    external:
      name: lnmp

services:
  directus:
    image: directus/directus:v8-apache
    ports:
      - "9090:80"
    environment:
      DIRECTUS_APP_ENV: "production"
      DIRECTUS_AUTH_PUBLICKEY: "123"
      DIRECTUS_AUTH_SECRETKEY: "123"
      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "root"
      DIRECTUS_DATABASE_PASSWORD: "123"
    volumes:
      - ./data/config:/var/directus/config
      - ./data/uploads:/var/directus/public/uploads    
    networks:
      - directus