version: '3.7'
services:
    nginx:
        image: "${NAME_SPACE}/nginx:v1.0"
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - "$PWD/nginx/conf.d:/etc/nginx/conf.d"
            - "${PROJECT_PATH}:/var/www/html:cached"
        ports:
            - "80:80"
        networks:
            lnmp:
                aliases:
                    - ${SERVICE_HOST}
                    - ${VIDEO_HOST}
        depends_on:
            - php
            - php6
    redis:
        image: "${NAME_SPACE}/redis:v1.0"
        restart: always
        build:
            context: ./redis
            dockerfile: Dockerfile
        networks:
            - lnmp
    php:
        image: "${NAME_SPACE}/php:v1.0"
        restart: always
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - "${PROJECT_PATH}:/var/www/html:cached"
        networks:
            - lnmp
        depends_on:
            - mysql
            - redis
    php6:
        image: "${NAME_SPACE}/php6:v1.0"
        restart: always
        build:
            context: ./php6
            dockerfile: Dockerfile
        volumes:
            - "${PROJECT_PATH}:/var/www/html:cached"
        networks:
            - lnmp
        depends_on:
            - mysql
            - redis
    phpcli:
        image: "${NAME_SPACE}/phpcli:v1.0"
        restart: always
        build:
            context: ./phpcli
            dockerfile: Dockerfile
        networks:
            - lnmp
        depends_on:
            - redis
    phpcli6:
        image: "${NAME_SPACE}/phpcli6:v1.0"
        restart: always
        build:
            context: ./phpcli6
            dockerfile: Dockerfile
        networks:
            - lnmp
        depends_on:
            - redis
    mysql:
        image: "${NAME_SPACE}/mysql:v1.0"
        restart: always
        build:
            context: ./mysql
            dockerfile: Dockerfile
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            TZ: 'Asia/Shanghai'
            MYSQL_ROOT_PASSWORD: 111111
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - lnmp
volumes:
    mysql_data:

networks:
    lnmp:
