version: '3'
services:
    nginx:
        image: "${NAME_SPACE}/nginx:v1.0"
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - "$PWD/nginx/conf.d:/etc/nginx/conf.d"
            - "/Users/zzz/data/project:/var/www/html"
        ports:
            - "80:80"
        networks:
            - nginx
        depends_on:
            - php
    php:
        image: "${NAME_SPACE}/php:v1.0"
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - "/Users/zzz/data/project:/var/www/html"
        networks:
            - php
            - nginx
            - mysql
        depends_on:
            - mysql
    phpcli:
        image: "${NAME_SPACE}/phpcli:v1.0"
        build:
            context: ./phpcli
            dockerfile: Dockerfile
        volumes:
            - "/Users/zzz/data/project:/var/www/html"
        networks:
            - phpcli
            - php
            - nginx
            - mysql
    mysql:
        image: "${NAME_SPACE}/mysql:v1.0"
        build:
            context: ./mysql
            dockerfile: Dockerfile
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            TZ: 'Asia/Shanghai'
            MYSQL_ROOT_PASSWORD: 111111
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - mysql
volumes:
    mysql_data:

networks:
    php:
    phpcli:
    nginx:
    mysql:
